
POST http://127.0.0.1:3000/send-sms-code HTTP/1.1
x-rapidapi-proxy-secret:asd
content-type: application/json

{
    "to_phone_number": "6475807443",
    "verify_code": "756341",
    "app_name": "Peeqq"
}


###


POST http://127.0.0.1:3000/send-email-code HTTP/1.1
x-rapidapi-proxy-secret:asd
content-type: application/json

{
    "to_email": "killop1997@gmail.com",
    "verify_code": "756341",
    "app_name": "Peeqq"
}

###

POST https://smsverifsender-production.up.railway.app/ HTTP/1.1
x-rapidapi-proxy-secret:asd
content-type: application/json

{
    "to_phone_number": "+16473",
    "verify_code": "756341",
    "app_name": "SMS Sender"
}


###

POST https://email-sender.killop1997.workers.dev/ HTTP/1.1
content-type: application/json

{
"apiKey":"c92ec923-6fc3-4f30-a546-c0aead27068c",
"to_email":"killop1997@gmail.com",
"toName":"User",
"fromName":"App Name",
"subject":"Greate subject dude!",
"contentHTML":"This is the link I told you about https://super-apis.com"
}
