


POST https://smsverifsender-production.up.railway.app/ HTTP/1.1
x-rapidapi-proxy-secret:asd
content-type: application/json

{
    "phoneNumber": "+16473",
    "verifyCode": "756341",
    "appName": "SMS Sender"
}