


POST https://smsverifsender-production.up.railway.app/ HTTP/1.1
x-rapidapi-proxy-secret:""
content-type: application/json

{
    "phoneNumber": "+164744807443",
    "verifyCode": "756341",
    "appName": "SMS Sender"
}